# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    # Every week
    schedule:
      interval: 'weekly'

  # Enable version updates for Python/Pip - Production
  - package-ecosystem: 'pip'
    # Look for a `requirements.txt` in the `root` directory
    # also 'pyproject.toml', 'setup.cfg', 'runtime.txt' and 'requirements/*.txt'
    directory: '/'
    # Every week
    schedule:
      interval: 'weekly'
